# Generated by Django 3.1.7 on 2021-04-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperID', models.CharField(max_length=9)),
                ('abstract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paperID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('paperTitle', models.TextField()),
                ('publicationDate', models.CharField(max_length=7)),
                ('paperLocation', models.TextField()),
                ('paperDOI', models.TextField()),
                ('numCitation', models.IntegerField()),
                ('numReference', models.IntegerField()),
                ('numExistedReference', models.IntegerField()),
                ('numNotinRGReference', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.TextField(null=True)),
                ('paperID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paper.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceNotInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notReference', models.TextField()),
                ('paperID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paper.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceIdx', models.TextField()),
                ('paperID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paper.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='RealErrorInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('errCnt', models.IntegerField()),
                ('paperID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paper.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('paperID', models.ForeignKey(db_column='paperID', default=1, on_delete=django.db.models.deletion.CASCADE, to='paper.paperinfo')),
            ],
        ),
    ]
