# Generated by Django 3.1.7 on 2021-04-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('arxiv_num', models.CharField(max_length=20)),
                ('pdf_url', models.CharField(max_length=50)),
                ('publication_year', models.CharField(max_length=4)),
                ('publication_month', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='arxiv.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='arxiv.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='arxiv.paperinfo')),
            ],
        ),
    ]
