# Generated by Django 3.1.7 on 2021-04-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paperID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('arxiv_num', models.CharField(max_length=20)),
                ('pdf_url', models.CharField(max_length=50)),
                ('publication_year', models.CharField(max_length=4)),
                ('publication_month', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('paperID_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('paperID_authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.paperinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('paperID_abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arxiv.paperinfo')),
            ],
        ),
    ]
