# Generated by Django 3.1.7 on 2021-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_auto_20210418_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='arxiv_num',
            field=models.CharField(max_length=20),
        ),
    ]
