# Generated by Django 3.1.7 on 2021-05-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paper_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('pdf_urls', models.TextField()),
                ('authors', models.TextField()),
                ('citation_list', models.TextField()),
                ('reference_list', models.TextField()),
                ('field_list', models.TextField()),
                ('publication_year', models.CharField(max_length=4)),
                ('venue', models.TextField(blank=True)),
                ('journal_name', models.TextField(blank=True)),
                ('journal_volume', models.TextField(blank=True)),
                ('journal_pages', models.TextField(blank=True, max_length=20)),
                ('doi', models.TextField(blank=True)),
                ('mag_id', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
