#!/bin/bash

cd /paperflow_server/paperflowServer

python3 manage.py makemigrations
python3 manage.py migrate

[ "$PYTHON_ENV" == "development" ] && (python3 manage.py runserver 0.0.0.0:8000) || (python3 manage.py runserver 0.0.0.0:8000)
