# Generated by Django 3.1.7 on 2021-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='abstractinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authorsinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='paperID',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='realerrorinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referenceinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referencenotinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='themeinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
