# Generated by Django 3.1.7 on 2021-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20210404_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
