# Generated by Django 3.1.7 on 2021-04-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_auto_20210404_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsinfo',
            name='paperID',
            field=models.ForeignKey(db_column='paperID', default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.paperinfo'),
        ),
        migrations.AlterField(
            model_name='realerrorinfo',
            name='paperID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.paperinfo'),
        ),
        migrations.AlterField(
            model_name='referenceinfo',
            name='paperID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.paperinfo'),
        ),
        migrations.AlterField(
            model_name='referencenotinfo',
            name='paperID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.paperinfo'),
        ),
        migrations.AlterField(
            model_name='themeinfo',
            name='paperID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.paperinfo'),
        ),
    ]
